import { Student, Teacher, SchoolClass, StudentGradeRecord, StudentAttendanceRecord, TeacherAttendanceRecord, SubjectDefinition } from '../types';

export const GRADE_9_SUBJECTS: SubjectDefinition[] = [
  { id: 'sub_1', name: 'តែងសេចក្តី', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_2', name: 'អក្សរសាស្ត្រខ្មែរ', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_3', name: 'គណិតវិទ្យា', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_4', name: 'រូបវិទ្យា', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_5', name: 'គីមីវិទ្យា', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_6', name: 'ជីវវិទ្យា', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_7', name: 'ផែនដី និងបរិស្ថានវិទ្យា', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_8', name: 'ប្រវត្តិវិទ្យា', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_9', name: 'ភូមិវិទ្យា', coefficient: 1, gradeLevel: '9' },
  { id: 'sub_10', name: 'សីលធម៌-ពលរដ្ឋវិទ្យា', coefficient: 1, gradeLevel: '9' },
];

export const GRADE_1_8_SUBJECTS: SubjectDefinition[] = [
  { id: 'sub_1', name: 'តែងសេចក្តី', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_2', name: 'អក្សរសាស្ត្រខ្មែរ', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_3', name: 'គណិតវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_4', name: 'រូបវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_5', name: 'គីមីវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_6', name: 'ជីវវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_7', name: 'ផែនដី និងបរិស្ថានវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_8', name: 'ប្រវត្តិវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_9', name: 'ភូមិវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_10', name: 'សីលធម៌-ពលរដ្ឋវិទ្យា', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_11', name: 'ភាសាបរទេស (អង់គ្លេស)', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_12', name: 'គេហវិទ្យា និងសិល្បៈ', coefficient: 1, gradeLevel: '1-8' },
  { id: 'sub_13', name: 'អប់រំកាយ និងកីឡា', coefficient: 1, gradeLevel: '1-8' },
];

export const ACADEMIC_MONTHS = [
  'តេស្តដើមឆ្នាំ',
  'ខែវិច្ឆិកា',
  'ខែធ្នូ',
  'ខែមករា',
  'ខែកុម្ភៈ',
  'ខែមីនា',
  'ខែមេសា',
  'ខែឧសភា',
  'ខែមិថុនា',
  'ខែកក្កដា',
  'ខែសីហា',
  'ខែកញ្ញា',
  'ខែតុលា',
] as const;

export const SEMESTER_1_MONTHS = ['ខែធ្នូ', 'ខែមករា', 'ខែកុម្ភៈ'] as const;
export const SEMESTER_2_MONTHS = ['ខែឧសភា', 'ខែមិថុនា', 'ខែកក្កដា'] as const;

export const INITIAL_CLASSES: SchoolClass[] = [
  {
    id: 'cls-7a',
    name: 'ថ្នាក់ទី ៧ក',
    level: 7,
    academicYear: '2025-2026',
    roomNumber: 'បន្ទប់ ១០១',
    homeroomTeacherId: 'T-001',
    studentIds: ['STU-001', 'STU-002', 'STU-003', 'STU-004'],
    description: 'ថ្នាក់អនុវិទ្យាល័យ វេនព្រឹក',
  },
  {
    id: 'cls-7b',
    name: 'ថ្នាក់ទី ៧ខ',
    level: 7,
    academicYear: '2025-2026',
    roomNumber: 'បន្ទប់ ១០២',
    homeroomTeacherId: 'T-002',
    studentIds: ['STU-005', 'STU-006'],
    description: 'ថ្នាក់អនុវិទ្យាល័យ វេនរសៀល',
  },
  {
    id: 'cls-8a',
    name: 'ថ្នាក់ទី ៨ក',
    level: 8,
    academicYear: '2025-2026',
    roomNumber: 'បន្ទប់ ២០១',
    homeroomTeacherId: 'T-003',
    studentIds: ['STU-007', 'STU-008'],
    description: 'ថ្នាក់អនុវិទ្យាល័យ វេនព្រឹក',
  },
  {
    id: 'cls-9a',
    name: 'ថ្នាក់ទី ៩ក',
    level: 9,
    academicYear: '2025-2026',
    roomNumber: 'បន្ទប់ ៣០១',
    homeroomTeacherId: 'T-004',
    studentIds: ['STU-009', 'STU-010', 'STU-011'],
    description: 'ថ្នាក់ត្រៀមប្រឡងឌីប្លូម វេនព្រឹក',
  },
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: 'T-001',
    name: 'សុខ វិបុល',
    gender: 'ប្រុស',
    dob: '1985-04-12',
    specialty: 'គណិតវិទ្យា',
    currentRole: 'គ្រូបង្រៀនកម្រិតមូលដ្ឋាន',
    entryDate: '2008-10-01',
    seniority: '១៨ ឆ្នាំ',
    address: 'សង្កាត់ទួលសង្កែ ខណ្ឌឫស្សីកែវ រាជធានីភ្នំពេញ',
    phoneNumber: '012 345 678',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    assignedClass: 'ថ្នាក់ទី ៧ក',
  },
  {
    id: 'T-002',
    name: 'ចាន់ ស្រីមុំ',
    gender: 'ស្រី',
    dob: '1990-08-25',
    specialty: 'អក្សរសាស្ត្រខ្មែរ',
    currentRole: 'គ្រូបង្រៀន និងប្រធានក្រុមបច្ចេកទេស',
    entryDate: '2014-11-15',
    seniority: '១២ ឆ្នាំ',
    address: 'សង្កាត់បឹងកក់១ ខណ្ឌទួលគោក រាជធានីភ្នំពេញ',
    phoneNumber: '098 765 432',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
    assignedClass: 'ថ្នាក់ទី ៧ខ',
  },
  {
    id: 'T-003',
    name: 'ហេង វណ្ណដា',
    gender: 'ប្រុស',
    dob: '1988-02-18',
    specialty: 'រូបវិទ្យា',
    currentRole: 'គ្រូបង្រៀន',
    entryDate: '2012-09-01',
    seniority: '១៤ ឆ្នាំ',
    address: 'សង្កាត់ស្ទឹងមានជ័យ ខណ្ឌមានជ័យ រាជធានីភ្នំពេញ',
    phoneNumber: '087 112 233',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    assignedClass: 'ថ្នាក់ទី ៨ក',
  },
  {
    id: 'T-004',
    name: 'កែវ សុភា',
    gender: 'ស្រី',
    dob: '1982-12-05',
    specialty: 'គីមីវិទ្យា',
    currentRole: 'នាយករងទទួលបន្ទុកសិក្សា',
    entryDate: '2005-10-01',
    seniority: '២១ ឆ្នាំ',
    address: 'សង្កាត់ចោមចៅ ខណ្ឌពោធិ៍សែនជ័យ រាជធានីភ្នំពេញ',
    phoneNumber: '077 554 433',
    image: 'https://images.unsplash.com/photo-1580894732488-8120b22a0134?auto=format&fit=crop&q=80&w=300',
    assignedClass: 'ថ្នាក់ទី ៩ក',
  },
  {
    id: 'T-005',
    name: 'លី រតនា',
    gender: 'ប្រុស',
    dob: '1993-06-30',
    specialty: 'ភាសាបរទេស (អង់គ្លេស)',
    currentRole: 'គ្រូបង្រៀនកិច្ចសន្យា',
    entryDate: '2019-01-10',
    seniority: '៧ ឆ្នាំ',
    address: 'សង្កាត់ភ្នំពេញថ្មី ខណ្ឌសែនសុខ រាជធានីភ្នំពេញ',
    phoneNumber: '096 889 900',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    assignedClass: 'ថ្នាក់ទី ៧ក',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'STU-001',
    name: 'កែវ ពិសិដ្ឋ',
    gender: 'ប្រុស',
    dob: '2013-05-14',
    grade: 'ថ្នាក់ទី ៧ក',
    motherName: 'អ៊ុំ សុខា',
    fatherName: 'កែវ វិបុល',
    address: 'ភូមិ១ សង្កាត់ទឹកថ្លា ខណ្ឌសែនសុខ',
    phoneNumber: '012 998 877',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-002',
    name: 'ឆាយ ចរិយា',
    gender: 'ស្រី',
    dob: '2013-09-20',
    grade: 'ថ្នាក់ទី ៧ក',
    motherName: 'ម៉ៅ សុផល',
    fatherName: 'ឆាយ គឹមសាន',
    address: 'ភូមិព្រែកតាគង់ សង្កាត់ចាក់អង្រែលើ',
    phoneNumber: '093 445 566',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-003',
    name: 'ទូច បូរ៉ា',
    gender: 'ប្រុស',
    dob: '2013-02-11',
    grade: 'ថ្នាក់ទី ៧ក',
    motherName: 'សេង ស្រីពៅ',
    fatherName: 'ទូច ចំរើន',
    address: 'ភូមិដីថ្មី សង្កាត់គោកឃ្លាង',
    phoneNumber: '088 123 999',
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-004',
    name: 'ម៉ៅ ស្រីណែត',
    gender: 'ស្រី',
    dob: '2013-11-04',
    grade: 'ថ្នាក់ទី ៧ក',
    motherName: 'យូ គឹមអេង',
    fatherName: 'ម៉ៅ វ៉ាន់នី',
    address: 'សង្កាត់ទួលទំពូង១ ខណ្ឌចំការមន',
    phoneNumber: '011 223 344',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-005',
    name: 'នួន វណ្ណី',
    gender: 'ប្រុស',
    dob: '2013-07-08',
    grade: 'ថ្នាក់ទី ៧ខ',
    motherName: 'ស៊ន វ៉ាន់ដា',
    fatherName: 'នួន សារ៉េត',
    address: 'សង្កាត់បឹងកេងកង៣ ខណ្ឌបឹងកេងកង',
    phoneNumber: '070 334 455',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-006',
    name: 'រ័ត្ន ធីតា',
    gender: 'ស្រី',
    dob: '2013-03-29',
    grade: 'ថ្នាក់ទី ៧ខ',
    motherName: 'ជួន រតនា',
    fatherName: 'រ័ត្ន ផល្លី',
    address: 'សង្កាត់ស្រះចក ខណ្ឌដូនពេញ',
    phoneNumber: '015 667 788',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-007',
    name: 'ឡាយ ដានីល',
    gender: 'ប្រុស',
    dob: '2012-08-16',
    grade: 'ថ្នាក់ទី ៨ក',
    motherName: 'កែវ វណ្ណារី',
    fatherName: 'ឡាយ វ៉ាន់ថន',
    address: 'សង្កាត់ផ្សារដេប៉ូ៣ ខណ្ឌទួលគោក',
    phoneNumber: '097 554 433',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-008',
    name: 'គឹម លីហួរ',
    gender: 'ប្រុស',
    dob: '2012-10-12',
    grade: 'ថ្នាក់ទី ៨ក',
    motherName: 'ឆេង ផល្លា',
    fatherName: 'គឹម ហាក់',
    address: 'សង្កាត់ចោមចៅ៣ ខណ្ឌពោធិ៍សែនជ័យ',
    phoneNumber: '012 887 766',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-009',
    name: 'ហេង មុនីរ័ត្ន',
    gender: 'ស្រី',
    dob: '2011-01-19',
    grade: 'ថ្នាក់ទី ៩ក',
    motherName: 'សាន សុខនី',
    fatherName: 'ហេង សុវណ្ណ',
    address: 'សង្កាត់បឹងសាឡាង ខណ្ឌទួលគោក',
    phoneNumber: '089 990 011',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-010',
    name: 'សុខ វិបុលចិត្រ',
    gender: 'ប្រុស',
    dob: '2011-05-22',
    grade: 'ថ្នាក់ទី ៩ក',
    motherName: 'តាំង គឹមឡេង',
    fatherName: 'សុខ សារ៉ាត់',
    address: 'សង្កាត់ព្រែកព្នៅ ខណ្ឌព្រែកព្នៅ',
    phoneNumber: '017 665 544',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
  {
    id: 'STU-011',
    name: 'អ៊ុក សុជាតា',
    gender: 'ស្រី',
    dob: '2011-09-05',
    grade: 'ថ្នាក់ទី ៩ក',
    motherName: 'ពេជ្រ ស្រីម៉ៅ',
    fatherName: 'អ៊ុក វិចិត្រ',
    address: 'សង្កាត់ស្ទឹងមានជ័យ២ ខណ្ឌមានជ័យ',
    phoneNumber: '098 332 211',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
    status: 'កំពុងរៀន',
    createdAt: '2025-09-01',
  },
];

export const INITIAL_GRADES: StudentGradeRecord[] = [
  {
    id: 'GRD-001',
    studentId: 'STU-001',
    studentName: 'កែវ ពិសិដ្ឋ',
    gradeClass: 'ថ្នាក់ទី ៧ក',
    month: 'ខែធ្នូ',
    academicYear: '2025-2026',
    subjects: {
      'តែងសេចក្តី': 42,
      'អក្សរសាស្ត្រខ្មែរ': 45,
      'គណិតវិទ្យា': 48,
      'រូបវិទ្យា': 40,
      'គីមីវិទ្យា': 38,
      'ជីវវិទ្យា': 44,
      'ផែនដី និងបរិស្ថានវិទ្យា': 41,
      'ប្រវត្តិវិទ្យា': 46,
      'ភូមិវិទ្យា': 43,
      'សីលធម៌-ពលរដ្ឋវិទ្យា': 47,
      'ភាសាបរទេស (អង់គ្លេស)': 45,
      'គេហវិទ្យា និងសិល្បៈ': 44,
      'អប់រំកាយ និងកីឡា': 49,
    },
    totalScore: 572,
    averageScore: 44.0,
    gradeRank: 1,
    gradeLetter: 'ល្អប្រសើរ (A)',
    updatedAt: '2025-12-28',
  },
  {
    id: 'GRD-002',
    studentId: 'STU-002',
    studentName: 'ឆាយ ចរិយា',
    gradeClass: 'ថ្នាក់ទី ៧ក',
    month: 'ខែធ្នូ',
    academicYear: '2025-2026',
    subjects: {
      'តែងសេចក្តី': 45,
      'អក្សរសាស្ត្រខ្មែរ': 46,
      'គណិតវិទ្យា': 44,
      'រូបវិទ្យា': 42,
      'គីមីវិទ្យា': 40,
      'ជីវវិទ្យា': 45,
      'ផែនដី និងបរិស្ថានវិទ្យា': 43,
      'ប្រវត្តិវិទ្យា': 45,
      'ភូមិវិទ្យា': 44,
      'សីលធម៌-ពលរដ្ឋវិទ្យា': 48,
      'ភាសាបរទេស (អង់គ្លេស)': 43,
      'គេហវិទ្យា និងសិល្បៈ': 46,
      'អប់រំកាយ និងកីឡា': 48,
    },
    totalScore: 579,
    averageScore: 44.54,
    gradeRank: 1,
    gradeLetter: 'ល្អប្រសើរ (A)',
    updatedAt: '2025-12-28',
  },
  {
    id: 'GRD-003',
    studentId: 'STU-009',
    studentName: 'ហេង មុនីរ័ត្ន',
    gradeClass: 'ថ្នាក់ទី ៩ក',
    month: 'ខែធ្នូ',
    academicYear: '2025-2026',
    subjects: {
      'តែងសេចក្តី': 45,
      'អក្សរសាស្ត្រខ្មែរ': 48,
      'គណិតវិទ្យា': 46,
      'រូបវិទ្យា': 44,
      'គីមីវិទ្យា': 42,
      'ជីវវិទ្យា': 47,
      'ផែនដី និងបរិស្ថានវិទ្យា': 43,
      'ប្រវត្តិវិទ្យា': 48,
      'ភូមិវិទ្យា': 45,
      'សីលធម៌-ពលរដ្ឋវិទ្យា': 49,
    },
    totalScore: 457,
    averageScore: 45.7,
    gradeRank: 1,
    gradeLetter: 'ល្អប្រសើរ (A)',
    updatedAt: '2025-12-28',
  },
  {
    id: 'GRD-004',
    studentId: 'STU-010',
    studentName: 'សុខ វិបុលចិត្រ',
    gradeClass: 'ថ្នាក់ទី ៩ក',
    month: 'ខែធ្នូ',
    academicYear: '2025-2026',
    subjects: {
      'តែងសេចក្តី': 39,
      'អក្សរសាស្ត្រខ្មែរ': 41,
      'គណិតវិទ្យា': 45,
      'រូបវិទ្យា': 40,
      'គីមីវិទ្យា': 38,
      'ជីវវិទ្យា': 41,
      'ផែនដី និងបរិស្ថានវិទ្យា': 39,
      'ប្រវត្តិវិទ្យា': 42,
      'ភូមិវិទ្យា': 40,
      'សីលធម៌-ពលរដ្ឋវិទ្យា': 44,
    },
    totalScore: 409,
    averageScore: 40.9,
    gradeRank: 2,
    gradeLetter: 'ល្អណាស់ (B)',
    updatedAt: '2025-12-28',
  },
  {
    id: 'GRD-005',
    studentId: 'STU-001',
    studentName: 'កែវ ពិសិដ្ឋ',
    gradeClass: 'ថ្នាក់ទី ៧ក',
    month: 'ខែមករា',
    academicYear: '2025-2026',
    subjects: {
      'តែងសេចក្តី': 44,
      'អក្សរសាស្ត្រខ្មែរ': 46,
      'គណិតវិទ្យា': 49,
      'រូបវិទ្យា': 42,
      'គីមីវិទ្យា': 40,
      'ជីវវិទ្យា': 45,
      'ផែនដី និងបរិស្ថានវិទ្យា': 43,
      'ប្រវត្តិវិទ្យា': 47,
      'ភូមិវិទ្យា': 44,
      'សីលធម៌-ពលរដ្ឋវិទ្យា': 48,
      'ភាសាបរទេស (អង់គ្លេស)': 46,
      'គេហវិទ្យា និងសិល្បៈ': 45,
      'អប់រំកាយ និងកីឡា': 50,
    },
    totalScore: 589,
    averageScore: 45.3,
    gradeRank: 1,
    gradeLetter: 'ល្អប្រសើរ (A)',
    updatedAt: '2026-01-29',
  },
  {
    id: 'GRD-006',
    studentId: 'STU-001',
    studentName: 'កែវ ពិសិដ្ឋ',
    gradeClass: 'ថ្នាក់ទី ៧ក',
    month: 'ខែកុម្ភៈ',
    academicYear: '2025-2026',
    subjects: {
      'តែងសេចក្តី': 43,
      'អក្សរសាស្ត្រខ្មែរ': 47,
      'គណិតវិទ្យា': 48,
      'រូបវិទ្យា': 41,
      'គីមីវិទ្យា': 39,
      'ជីវវិទ្យា': 44,
      'ផែនដី និងបរិស្ថានវិទ្យា': 42,
      'ប្រវត្តិវិទ្យា': 46,
      'ភូមិវិទ្យា': 43,
      'សីលធម៌-ពលរដ្ឋវិទ្យា': 47,
      'ភាសាបរទេស (អង់គ្លេស)': 44,
      'គេហវិទ្យា និងសិល្បៈ': 45,
      'អប់រំកាយ និងកីឡា': 49,
    },
    totalScore: 578,
    averageScore: 44.46,
    gradeRank: 1,
    gradeLetter: 'ល្អប្រសើរ (A)',
    updatedAt: '2026-02-27',
  }
];

export const INITIAL_STUDENT_ATTENDANCE: StudentAttendanceRecord[] = [
  {
    id: 'ATT-S-001',
    date: '2026-02-28',
    classId: 'cls-7a',
    className: 'ថ្នាក់ទី ៧ក',
    studentId: 'STU-001',
    studentName: 'កែវ ពិសិដ្ឋ',
    subject: 'គណិតវិទ្យា',
    teacherName: 'សុខ វិបុល',
    teacherId: 'T-001',
    status: 'ចូលរៀន',
    note: '',
  },
  {
    id: 'ATT-S-002',
    date: '2026-02-28',
    classId: 'cls-7a',
    className: 'ថ្នាក់ទី ៧ក',
    studentId: 'STU-002',
    studentName: 'ឆាយ ចរិយា',
    subject: 'គណិតវិទ្យា',
    teacherName: 'សុខ វិបុល',
    teacherId: 'T-001',
    status: 'ចូលរៀន',
    note: '',
  },
  {
    id: 'ATT-S-003',
    date: '2026-02-28',
    classId: 'cls-7a',
    className: 'ថ្នាក់ទី ៧ក',
    studentId: 'STU-003',
    studentName: 'ទូច បូរ៉ា',
    subject: 'គណិតវិទ្យា',
    teacherName: 'សុខ វិបុល',
    teacherId: 'T-001',
    status: 'ច្បាប់',
    note: 'គ្រុនក្តៅ',
  },
  {
    id: 'ATT-S-004',
    date: '2026-02-28',
    classId: 'cls-7a',
    className: 'ថ្នាក់ទី ៧ក',
    studentId: 'STU-004',
    studentName: 'ម៉ៅ ស្រីណែត',
    subject: 'គណិតវិទ្យា',
    teacherName: 'សុខ វិបុល',
    teacherId: 'T-001',
    status: 'ចូលរៀន',
    note: '',
  },
];

export const INITIAL_TEACHER_ATTENDANCE: TeacherAttendanceRecord[] = [
  {
    id: 'ATT-T-001',
    date: '2026-02-28',
    teacherId: 'T-001',
    teacherName: 'សុខ វិបុល',
    subject: 'គណិតវិទ្យា',
    checkInTime: '06:55',
    checkOutTime: '11:00',
    status: 'ទាន់ម៉ោង',
    note: 'បង្រៀនម៉ោងទី១-២',
  },
  {
    id: 'ATT-T-002',
    date: '2026-02-28',
    teacherId: 'T-002',
    teacherName: 'ចាន់ ស្រីមុំ',
    subject: 'អក្សរសាស្ត្រខ្មែរ',
    checkInTime: '07:10',
    checkOutTime: '11:00',
    status: 'យឺត',
    note: 'ស្ទះចរាចរណ៍លើផ្លូវជាតិ',
  },
  {
    id: 'ATT-T-003',
    date: '2026-02-28',
    teacherId: 'T-003',
    teacherName: 'ហេង វណ្ណដា',
    subject: 'រូបវិទ្យា',
    checkInTime: '07:00',
    checkOutTime: '11:00',
    status: 'ទាន់ម៉ោង',
    note: '',
  },
  {
    id: 'ATT-T-004',
    date: '2026-02-28',
    teacherId: 'T-004',
    teacherName: 'កែវ សុភា',
    subject: 'គីមីវិទ្យា',
    checkInTime: '-',
    checkOutTime: '-',
    status: 'ច្បាប់',
    note: 'ចូលរួមកិច្ចប្រជុំក្រសួងអប់រំ',
  },
];
